version: "{build}"
init:
  - git config --global core.autocrlf input
environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - cmd: npm test --no-color
cache:
  - node_modules -> package.json
  - "%APPDATA%\\npm-cache -> package.json"
skip_tags: true
matrix:
  fast_finish: true
notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
